### ISSUE TITLE
Checklist launch in The Netherlands

### ISSUE THREAD

**Issue by adriaandotcom** [BustByte/coronastatus.no#249]
- [x] [Change questions](https://github.com/BustByte/coronastatus/issues/245) @jelbazi 
- [x] Update stats for Norway @fossecode 
- [x] [Implement design](https://github.com/BustByte/coronastatus/issues/191) @NickolasBoyer 
- [x] [Create ads and meta images](https://github.com/BustByte/coronastatus/issues/250) @amritnagi
- [x] [Check SEO data](https://github.com/BustByte/coronastatus/issues/223) @adriaanvanrossum
- [x] Make map center around country
- [ ] Add share buttons for big platforms

Still open
- [x] Check translations
- [x] Check full flow
- [x] Check newly added fields https://github.com/BustByte/coronastatus/issues/245#issuecomment-602541268
- [x] Fix translations in our code https://github.com/BustByte/coronastatus/issues/245#issuecomment-602550440

**Comment by Kilian** [comment]
Translations have been checked in #247.

**Comment by fossecode** [comment]
Updated questions and stats for Norway in https://github.com/BustByte/coronastatus/pull/251.

**Comment by jelbazi** [comment]
Do we have a CTA on the Map page?

It is foreseeable that many users come to that page first (or again) to check the spread of Covid-19. 

It's an opportunity to funnel them into the survey (again).

**Comment by adriaandotcom** [comment]
> "Contribute now" seems good for people who didn’t leave their info yet. "Your health" is great for people we did.

https://t.me/onzecorona/1862

**Comment by adriaandotcom** [comment]
Done CTA in https://github.com/BustByte/coronastatus/pull/278

**Comment by adriaandotcom** [comment]
Closing..
