### ISSUE TITLE
Checklist launch in Slovakia

### ISSUE THREAD

**Issue by fossecode** [BustByte/coronastatus.no#256]
See checklist further down 👇

**Comment by fossecode** [comment]
@sbocinec I think we are almost ready to launch in Slovakia as well. Do you have time to look at the two things above?

**Comment by sbocinec** [comment]
Gonna work on this tonight, will keep you updated on the channel. Thank you!

**Comment by sbocinec** [comment]
- [x] Write privacy policy
- [x] Add missing translations in sk.json
- [x] Create social media images
- [x] Update the sk wordlist
- [x] Check translations
- [x] Enable Simple analytics
- [x] Enable Stadia maps

**Comment by fossecode** [comment]
Fantastic!

**Comment by michaelmcmillan** [comment]
I guess this can be closed
