### ISSUE TITLE
Checklist launch in Sweden 🇸🇪

### ISSUE THREAD

**Issue by ewels** [BustByte/coronastatus.no#321]
- [x]  Check privacy policy
- [x]  Add postcodes - https://github.com/BustByte/coronastatus/pull/319
- [x]  Write translations - https://github.com/BustByte/coronastatus/pull/419
- [x]  Make a `se` wordlist for passwords
- [x]  Configure URL paths in `app/domain/urls.ts` https://github.com/BustByte/coronastatus/pull/414
- [ ]  Check survey questions
- [x]  Get instance up and running - @talavis
- [ ]  **Get project approved locally**
- [ ]  Sort out domain name
- [ ]  `config.json` ready
- [ ]  Check full flow

Additional TODOs that can be post-launch:

- [ ] Language dropdown selector

**Comment by apelsinet** [comment]
Filed a PR for `Make a se wordlist for passwords` (#413)

**Comment by bjornhenriksson** [comment]
Filed a PR for `Configure URL paths in app/domain/urls.ts` (https://github.com/BustByte/coronastatus/pull/414)

**Comment by talavis** [comment]
I think we have translations ready for almost everything. Will ask them to make pr.

**Comment by bjornhenriksson** [comment]
@ewels heey! Can you elaborate on _Update stats for Sweden_ and _Check survey questions_ what do they mean? 😄

**Comment by ewels** [comment]
Hi @bjornhenriksson - thanks for your help above! I can't remember exactly what I meant by _Update stats for Sweden_ to be honest, I stole the list from another similar issue so it might not be relevant for us. _Check survey questions_ referred to our internal effort to be sure that the questions are exactly what we need before we launch.

See https://github.com/SciLifeLab/coronastatus/issues/6#issuecomment-604891653 for an update from us that I posted earlier today. Since I wrote that we have been in touch with the group behind the study discussed in https://github.com/BustByte/coronastatus/issues/245 so I hope to come back with more in the very near future (tomorrow or maybe Monday now I guess).

I appreciate that it probably feels like we're suddenly slowing down after a few intense days when the project is running so well and we basically have everything ready to launch a site. However, there is a lot of action behind the scenes right now and I hope that if we can do this in collaboration with the big players then we will be able to have a really positive national effect.

**Comment by apelsinet** [comment]
Nice work on the translation! It seems like the input for postal codes is capped at 4 characters which is problematic for Swedish postal codes 😄

**Comment by talavis** [comment]
> Nice work on the translation! It seems like the input for postal codes is capped at 4 characters which is problematic for Swedish postal codes 😄 

That's set in the config.

**Comment by apelsinet** [comment]
> > Nice work on the translation! It seems like the input for postal codes is capped at 4 characters which is problematic for Swedish postal codes 😄
> 
> That's set in the config.

Oh, nvm 😄
